trigger: none
# Don't run against PRs
pr: none

jobs:
  - job: run_monaco_deploy
    container: 
      image: dynatraceace/monaco-runner:latest
      options: --memory="4Gi" --cpus="2"
    strategy:
     matrix:
      Python38:
        python.version: '3.8'
    steps:
    - script: printenv
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath' 
        scriptPath: config/updateendpoints.py
        #arguments: # Optional
        #pythonInterpreter: # Optional
        #workingDirectory: # Optional
        #failOnStderr: false # Optional