trigger: none

# Don't run against PRs
pr: none

jobs:
  - job: run_monaco_deploy
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'DTS-CFTPTL-INTSVC'
        KeyVaultName: 'cftptl-intsvc'
        SecretsFilter: 'dynatrace-api-key-yrk32651,dynatrace-api-key-ebe20728'
        RunAsPreJob: true
    - task: AzureCLI@2
      displayName: 'Monaco deploy and update endpoint'
      env:
        nonprod_token: $(dynatrace-api-key-yrk32651)
        NEW_CLI: "1"
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        azureSubscription: 'DCD-CNP-DEV'
        scriptPath: config/deploy.sh