trigger: none
# Don't run against PRs
pr: none

jobs:
  - job: run_monaco_deploy
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: AzureCLI@2
      displayName: 'Monaco deploy and update endpoint'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        scriptPath: config/deploy.sh