trigger: none
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'DTS-CFTPTL-INTSVC'
    KeyVaultName: 'cftptl-intsvc'
    SecretsFilter: 'dynatrace-api-key-yrk32651,dynatrace-api-key-ebe20728'
    RunAsPreJob: true
# Don't run against PRs
pr: none

jobs:
  - job: run_monaco_deploy
    pool:
      vmImage: 'Ubuntu 18.04'
    steps:
    - task: AzureCLI@2
      displayName: 'Monaco deploy and update endpoint'
      inputs:
        scriptType: bash
        scriptLocation: scriptPath
        azureSubscription: 'DCD-CNP-DEV'
        scriptPath: config/deploy.sh