trigger: none
# Don't run against PRs
pr: none

jobs:
  - job: run_monaco_deploy
    container: dynatraceace/monaco-runner:release-v1.1.0
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 250m
          memory: 1Gi
    strategy:
     matrix:
      Python38:
        python.version: '3.8'
    steps:
    - script: printenv
    - task: PythonScript@0
      inputs:
        scriptSource: 'filePath' 
        scriptPath: config/updateendpoints.py
        #arguments: # Optional
        #pythonInterpreter: # Optional
        #workingDirectory: # Optional
        #failOnStderr: false # Optional